apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-node-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: kube-system
roleRef:
  kind: Role
  name: calico-node
  apiGroup: rbac.authorization.k8s.io
