apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${USER_DEPLOYMENT_NAME}
spec:
  replicas: ${USER_REPLICAS}
  selector:
    matchLabels:
      app: ${USER_DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${USER_DEPLOYMENT_NAME}
    spec:
      containers:
        - name: ${USER_CONTAINER_NAME}
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: ${USER_PORT}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "${USER_ENVIRONMENT}"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=${MYSQL_SERVICE_NAME};Port=${MYSQL_PORT};Database=${USER_DATABASE};User=root;Password=$Password;SslMode=None;AllowPublicKeyRetrieval=True;"
            - name: ConnectionStringsCredential__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ${USER_SECRET_NAME}
                  key: ${USER_SECRET_PASSWORD_KEY}
          # resources:
          #   requests:
          #     memory: "${USER_MEMORY_REQUEST}" # Set to 2 GB to meet the SQL Server requirement
          #     cpu: "${USER_CPU_REQUEST}" # Adjust CPU as necessary
          #   limits:
          #     memory: "${USER_MEMORY_LIMIT}" # Optional: Set a higher limit if you want to allow more usage
          #     cpu: "${USER_CPU_LIMIT}"

---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: ${USER_SERVICE_NAME}
spec:
  type: NodePort
  ports:
    - port: ${USER_PORT}
      targetPort: ${USER_PORT}
      nodePort: ${USER_NODE_PORT}
  selector:
    app: ${USER_DEPLOYMENT_NAME}
