apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-auth-deployment-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-auth-deployment-auth-service
  template:
    metadata:
      labels:
        app: staging-auth-deployment-auth-service
    spec:
      containers:
        - name: authservice
          image: huynhngocsonuit2000docker/fakebook-authservice:v004
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=staging-auth-service-mysql;Port=3306;Database=AuthDatabase;User=root;Password=$Password;SslMode=None;AllowPublicKeyRetrieval=True;"
            - name: ConnectionStringsCredential__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: staging-auth-secret-credential
                  key: ROOT_PASSWORD

---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: staging-auth-service-auth-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31005 # Expose on NodePort
  selector:
    app: staging-auth-deployment-auth-service
