apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-resource-quota
  namespace: staging-environment
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "0"           # Set to "0" for no limits
    limits.memory: "0"        # Set to "0" for no limits

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-resource-quota
  namespace: production-environment
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "0"           # Set to "0" for no limits
    limits.memory: "0"        # Set to "0" for no limits
