apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-fakebook-idp-deployment-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-fakebook-idp-deployment-api-service
  template:
    metadata:
      labels:
        app: staging-fakebook-idp-deployment-api-service
    spec:
      containers:
        - name: idpapiservice
          image: huynhngocsonuit2000docker/fakebook-idpapi:v003
          ports:
            - containerPort: 80
          volumeMounts:
            - name: private-key-volume
              mountPath: /app/keys/private_key.pem # Mount to this path in the container
              subPath: private_key.pem
      volumes:
        - name: private-key-volume
          secret:
            secretName: staging-idp-secret-private-key

---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: staging-fakebook-idp-service-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001 # Expose on NodePort
  selector:
    app: staging-fakebook-idp-deployment-api-service
