pipeline {
    agent any

    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['staging', 'production'],
            description: 'Choose the environment for deployment'
        )
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout code from the Git repository
                checkout scm
            }
        }

        stage('Restore NuGet Packages') {
            when {
                expression { env.ENVIRONMENT == 'production' }
            }
            steps {
                script {
                    sh 'dotnet restore src/test/FakebookIntegrationTests/FakebookIntegrationTests.sln'
                }
            }
        }
        
        stage('Integration Test') {
            when {
                expression { env.ENVIRONMENT == 'production' }
            }
            steps {
                echo 'Running unit tests...'
                sh 'dotnet test src/test/FakebookIntegrationTests/FakebookIntegrationTests.sln --configuration Release --no-restore --verbosity normal'
            }
        }

        stage('Generate Image Tag') {
            steps {
                script {
                    // Generate the image tag based on the current datetime
                    def now = new Date()
                    def formattedDate = now.format("yyyyMMdd-HHmmss")
                    env.IMAGE_TAG = formattedDate
                }
            }
        }

        stage('Load Global Configuration') {
            steps {
                script {
                    // Load service-specific configuration from config.groovy
                    def config = evaluate(readFile('Environments/Jenkins/global-config.groovy'))
                    def envConfig = evaluate(readFile("Environments/Jenkins/${params.ENVIRONMENT}-config.groovy"))

                    // Set environment variables from the configuration
                    env.KUBECONFIG = config.KUBECONFIG
                    env.KUBE_CONTEXT = config.KUBE_CONTEXT
                    env.DOCKER_CREDENTIAL_ID = config.DOCKER_CREDENTIAL_ID

                    env.NAMESPACE = envConfig.NAMESPACE
                }
            }
        }

        stage('Load Specific Configuration') {
            steps {
                script {
                    // Load service-specific configuration from config.groovy
                    def config = evaluate(readFile("./Environments/Jenkins/AuthService/${params.ENVIRONMENT}-config.groovy"))

                    // Set environment variables from the configuration
                    env.IMAGE_NAME = config.IMAGE_NAME
                    env.DOCKERFILE = config.DOCKERFILE
                    env.SECRET_CONFIGMAP_PATH = config.SECRET_CONFIGMAP_PATH
                    env.SERVICES_PATH = config.SERVICES_PATH

                    // Set environment variables for SQL and User Service
                    env.MYSQL_DEPLOYMENT_NAME = config.MYSQL_DEPLOYMENT_NAME
                    env.MYSQL_CONTAINER_NAME = config.MYSQL_CONTAINER_NAME
                    env.MYSQL_IMAGE = config.MYSQL_IMAGE
                    env.MYSQL_PORT = config.MYSQL_PORT.toString()
                    env.MYSQL_REPLICAS = config.MYSQL_REPLICAS.toString()
                    env.MYSQL_SECRET_NAME = config.MYSQL_SECRET_NAME
                    env.MYSQL_DEFAULT_DATABASE = config.MYSQL_DEFAULT_DATABASE
                    env.MYSQL_SECRET_PASSWORD_KEY = config.MYSQL_SECRET_PASSWORD_KEY
                    env.MYSQL_MEMORY_REQUEST = config.MYSQL_MEMORY_REQUEST
                    env.MYSQL_CPU_REQUEST = config.MYSQL_CPU_REQUEST
                    env.MYSQL_MEMORY_LIMIT = config.MYSQL_MEMORY_LIMIT
                    env.MYSQL_CPU_LIMIT = config.MYSQL_CPU_LIMIT
                    env.MYSQL_SERVICE_NAME = config.MYSQL_SERVICE_NAME

                    env.AUTH_DEPLOYMENT_NAME = config.AUTH_DEPLOYMENT_NAME
                    env.AUTH_CONTAINER_NAME = config.AUTH_CONTAINER_NAME
                    env.AUTH_PORT = config.AUTH_PORT.toString()
                    env.AUTH_REPLICAS = config.AUTH_REPLICAS.toString()
                    env.AUTH_ENVIRONMENT = config.AUTH_ENVIRONMENT
                    env.AUTH_DATABASE = config.AUTH_DATABASE
                    env.AUTH_SECRET_NAME = config.AUTH_SECRET_NAME
                    env.AUTH_SECRET_PASSWORD_KEY = config.AUTH_SECRET_PASSWORD_KEY
                    env.AUTH_SERVICE_NAME = config.AUTH_SERVICE_NAME
                    env.AUTH_NODE_PORT = config.AUTH_NODE_PORT.toString()
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image from Dockerfile
                    sh "docker build -t ${env.IMAGE_NAME}:${env.IMAGE_TAG} ./src -f ${env.DOCKERFILE}"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://index.docker.io/v1/", "${env.DOCKER_CREDENTIAL_ID}") {
                        // Push the Docker image to the registry
                        sh "docker push ${env.IMAGE_NAME}:${env.IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Deploy Secrets and ConfigMaps') {
            steps {
                script {
                    def secretFiles = findFiles(glob: "${env.SECRET_CONFIGMAP_PATH}")
                    secretFiles.each { file ->
                        echo "Applying secret or configmap: ${file.path}"
                        echo "Checking contexts"
                        echo "kubectl config get-contexts"
                        sh "kubectl get nodes"
                        sh "kubectl --context=${env.KUBE_CONTEXT} apply -f ${file.path} -n ${env.NAMESPACE}"
                    }
                }
            }
        }

        stage('Deploy Services') {
            steps {
                script {
                    def serviceFiles = findFiles(glob: "${env.SERVICES_PATH}")
                    serviceFiles.each { file ->
                        echo "Applying Service and Deployment: ${file.path}"

                        // Replace placeholders in each service file based on the ddconfig
                        def serviceYAML = readFile(file.path)
                        serviceYAML = serviceYAML.replaceAll(/\$\{([A-Z_]+)\}/) { env[it[1]] }

                        // Write the modified YAML back and apply it
                        writeFile file: file.path, text: serviceYAML
                        sh "kubectl --context=${KUBE_CONTEXT} apply -f ${file.path} -n ${env.NAMESPACE}"
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up the workspace after the job is completed
            cleanWs()
        }
    }
}
