Vagrant.configure("2") do |config|
    ### Number of worker nodes
    num_nodes = 2 # Change this number to create more worker nodes
  
    ### Master node configuration
    config.vm.define "smaster" do |master|
      master.vm.box = "centos/7"
      master.vm.hostname = "staging-k8s-master"
      master.vm.network "private_network", ip: "192.168.50.10"  # Master node's IP Address
      master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
  
      ### Provision scripts for master node
      master.vm.provision "shell", path: "./provision-env.sh"
      master.vm.provision "shell", path: "./../../SharedScripts/provision-docker.sh"
      master.vm.provision "shell", path: "./../../SharedScripts/provision-kubernetes.sh"
      master.vm.provision "shell", path: "./../../SharedScripts/provision-network.sh"
      master.vm.provision "shell", path: "./kubeadm-init-and-join.sh"
    end
  
    ## Worker nodes configuration
    (1..num_nodes).each do |i|
      config.vm.define "sworker#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "staging-k8s-worker#{i}"
        node.vm.network "private_network", ip: "192.168.50.#{10 + i}"   # Worker node's IP Address
        node.vm.provider "virtualbox" do |vb|
          vb.memory = 4096
          vb.cpus = 2
        end
  
        ### Provision scripts for worker nodes
        node.vm.provision "shell", path: "./provision-env.sh"
        node.vm.provision "shell", path: "./../../SharedScripts/provision-docker.sh"
        node.vm.provision "shell", path: "./../../SharedScripts/provision-kubernetes.sh"
        node.vm.provision "shell", path: "./../../SharedScripts/provision-network.sh"
        node.vm.provision "shell", path: "./kubeadm-init-and-join.sh"
        end
    end
  end